"""initial_migration

Revision ID: 0b717db82645
Revises: 
Create Date: 2025-10-01 14:25:25.245119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b717db82645'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tasks_active_unique', 'tasks', ['id'], unique=True, sqlite_where=sa.text('actual_start_time IS NOT NULL AND completed = 0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_active_unique', table_name='tasks', sqlite_where=sa.text('actual_start_time IS NOT NULL AND completed = 0'))
    # ### end Alembic commands ###
